成长型武器名: "§b§l⚝§d§l樱龙剑§b§l⚝"
龙剑伤害信息: "§7[§c系统§7] §e樱龙剑激活 §c体术攻击+"
#死亡信息世界名
world:
  - "fb3"
#掉级信息
message: '&d&l异梦结束 炁散百一'
#岩浆块造成的伤害
magma: 0
#仙人掌造成的伤害
touch: 0
#是否取消龙蛋传送
dragon-egg: true
#背景音乐世界
music:
  - "qyc"
#传送显示title的世界
title:
  - "qyc"
#显示的副标题
subtitle: ""
#渐入 显示 渐出
in: 20
on: 20
out: 20
#世界列表 第一排是title 第二排是music
qyc:
  - "§6炁源村"
  - "炁源村"
#默认技能模式
default-skill-mode: false
#禁止释放技能世界
skill-black:
  - "qyc"
  - "zz"
  - "qzsj"
  - "first"
skill-mode-title1: "&4战斗模式"
skill-mode-subtitle1: "&a可释放技能"
skill-mode-title2: "&a和平模式"
skill-mode-subtitle2: "&c不可释放技能"
egg-sound: "ENTITY_ENDERDRAGON_AMBIENT"
noskill-sound: "ENTITY_EVOCATION_ILLAGER_CAST_SPELL"
#禁止展示框与盔甲架交互世界
no-in-world:
  - "zhucheng"
  - "qzsj"
  - "zz"
  - "fb3"
SendMessage: "§a你不能在这个世界右键或者左键展示框,或者右键盔甲架"
#升级提示功能
前缀内容: "§7§l[§a等级系统§7§l] §b§l"
升级内容: " §e§l炁源 + 1！ §d§l"
降级内容: " §e§l炁源 - 1！ §d§l"
等级中间的内容: " §a➟ §d§l"
降级音乐: "降级"
升级音乐: "升级"
分割线: "§m#DB822116-FFFFFF00-DB822116                                               "