成长型武器名: "§b§l⚝§d§l樱龙剑§b§l⚝"
龙剑伤害信息: "§7[§c系统§7] §e樱龙剑激活 §c体术攻击+"
#死亡信息世界名
world:
  - "fb3"
#掉级信息
message: '&d&l异梦结束 炁散百一'
#岩浆块造成的伤害
magma: 0
#仙人掌造成的伤害
touch: 0
#是否取消龙蛋传送
dragon-egg: true
#背景音乐世界
music:
  - "qyc"
#传送显示title的世界
title:
  - "qyc"
#显示的副标题
subtitle: ""
#渐入 显示 渐出
in: 20
on: 20
out: 20
#世界列表 第一排是title 第二排是music
qyc:
  - "§6炁源村"
  - "炁源村"
#默认技能模式
default-skill-mode: false
#禁止释放技能世界
skill-black:
  - "qyc"
  - "zz"
  - "qzsj"
  - "first"
skill-mode-title1: "&4战斗模式"
skill-mode-subtitle1: "&a可释放技能"
skill-mode-title2: "&a和平模式"
skill-mode-subtitle2: "&c不可释放技能"
skill-mode-key: "KEY_R"